project:
  type: website
  output-dir: docs

website:
  title: "Игры и теория"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/Obsidian-pb/ObsidianBlog
format:
  html:
    theme: cosmo
    css: styles.css
lang: ru



